demo/config/routes.rb
Rails.application.routes.draw do
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    delete '/login', to: 'logins#destroy'
    resources :users do
        collection do
            get :allpost
        end
    end
    resources :announcements, :only=>[:index,:show]
    namespace :user do |user|
        resources :announcements
        resources :departments
    end
    #resources :login, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

demo/app/models/announcement.rb
class Announcement < ApplicationRecord
    belongs_to :department
    belongs_to :user
    validates_presence_of :title, :content
end

demo/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
    before_action :find_announcement, :only=>:show
    def index
        @page_title = "Bulletin Board"
        @announcements = Announcement.all
    end
    def show
        @page_title = @announcement.title
    end

private
    def find_announcement
        @announcement = Announcement.find(params[:id])
    end
end

demo/app/controllers/user/announcements_controller.rb
class User::AnnouncementsController < ApplicationController
	before_action :check
    before_action :find_announcement,:only=>[:show,:edit,:destroy,:update]
    def index
		@page_title = "Bulletin Board"
        @announcements = Announcement.all
    end
    def new
		@page_title = "New a New Announcement"
        @announcement = Announcement.new
    end
    def create
        @announcement = Announcement.new(announcement_params)
		@announcement.user_id = get_id
        if @announcement.save
            flash[:notice] = "A new announcement has been created successfully"
            redirect_to user_announcements_path
        else
            flash[:alert] = "Some field is not complete. Please retype again, thanks"
            render :action=>:new
        end
    end
    def show
		@page_title = @announcement.title
    end
    def edit
		if get_id==@announcement.user_id
			@page_title = "Edit "+@announcement.title
		else
			flash[:alert] = "Sorry about that, You are not the user who created this announcement"
			redirect_to user_announcements_path, :method=>:get
		end
    end
    def update
        if @announcement.update(announcement_params)
            flash[:notice] = "The announcement has been updated successfully"
            redirect_to user_announcements_path
        else
            flash[:alert] = "Some field is not complete. Please retype again, thanks"
            render :action=>:edit
        end
    end
    def destroy
		if get_id==@announcement.user_id
	        @announcement.destroy
	        flash[:notice] = "The announcement has been removed successfully"
	        redirect_to user_announcements_path
		else
			flash[:alert] = "Sorry about that, You are not the user who created this announcement"
			redirect_to user_announcements_path, :method=>:get
		end
    end
private
    def find_announcement
        @announcement = Announcement.find(params[:id])
    end
    def announcement_params
        params.require(:announcement).permit(:title,:content,:department_id,:user_id)
    end
    def check
        if !logged_in
            redirect_to announcements_url
        end
    end
end

demo/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

demo/app/helpers/user/announcements_helper.rb
module User::AnnouncementsHelper

end

demo/app/views/announcements/index.html.erb
<span class="h2" style="color:Blue;"><%= flash[:notice] %></span>
<span class="h2" style="color:Red;"><%= flash[:alert] %></span>
<nav class="navbar navbar-link">
    <% if logged_in%>
        <span style="font-size: 2rem">Hello, <%= @current_user.name%></span>
        <br />
        <div class="btn-group btn-group-lg">
            <%= link_to "Edit profile", edit_user_path(current_user), class:'btn btn-success'%>
            <%= link_to "Show profile", user_path(current_user), class:'btn btn-info' %>
            <%= link_to "Log Out", login_url,:method=>:delete, class:'btn btn-danger' %>
            <%= link_to "Show all department", user_departments_url, :class=>"btn btn-info" %>
        </div>
    <% else %>
        <br />
        <%= link_to "Login", login_url, :class=>"btn btn-info btn-lg"%>
    <% end %>
</nav>
<p style="color:Blue;font-size:2.5rem">
    Bulletin Board
</p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover h4">
      <tr>
        <td class="text-center">Updated Date</td>
        <td>Title</td>
        <td>Department</td>
      </tr>
        <% @announcements.each do |announcement| %>
        <tr>
            <td>
                <%=announcement.updated_at.localtime.strftime("%Y/%m/%d %H:%M:%S") %>
            </td>
            <td>
                <%=link_to announcement.title, announcement_path(announcement), :method=>:get%>
            </td>
            <td>
                <%= Department.find(announcement.department_id).d_name %>
            </td>
        </tr>
        <% end %>
    </table>
</div>
<% if logged_in %>
    <span><%= link_to "New Announcement", new_user_announcement_path,  class:'btn btn-primary btn-lg' %></span>
<% end %>

demo/app/views/announcements/show.html.erb
<p style="color : Green;">
    <%= flash[:notice] %>
</p>
<span style="font-size: 3rem">Announcement Title : <%= @announcement.title %></span>
<br/>
<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <tr class="h4">
            <td>
                Department :
            </td>
            <td>
                <%= Department.find(@announcement.department_id).d_name %>
            </td>
        </tr>
        <tr class="h4">
            <td colspan="2">
                <%= simple_format(@announcement.content) %>
            </td>
        </tr>
    </table>
</div>
<p style="font-size: 2rem;color: blue">
    <%= User.find_by(:id=>@announcement.user_id).name%> Posted it at <%= @announcement.created_at.localtime.strftime("%Y/%m/%d %H:%M:%S") %>
</p>
<p style="font-size: 2rem;color:Red">
    Update_Date : <%= @announcement.updated_at.localtime.strftime("%Y/%m/%d %H:%M:%S") %>
</p>
<p>
    <%= link_to "Back to index", announcements_path,:class=>"btn btn-primary btn-lg" %>
</p>