demo/config/routes.rb
Rails.application.routes.draw do
    get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    delete '/login', to: 'logins#destroy'
    resources :users do
        collection do
            get :allpost
        end
    end
    resources :announcements, :only=>[:index,:show]
    namespace :user do |user|
        resources :announcements
        resources :departments
    end
    #resources :login, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

demo/app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :name, :account, :email
    validates_presence_of :password, :on=>:create
    validates_length_of :name, maximum: 50
    validates_length_of :account, in: 8..16
    validates_length_of :password, in: 8..20,:on=>:create
    validates_length_of :email, maximum: 255
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates_format_of :email, with:VALID_EMAIL_REGEX
    validates_uniqueness_of :account
    has_secure_password
    has_many :announcements
end

demo/app/controllers/user/announcements_controller.rb
class User::AnnouncementsController < ApplicationController
	before_action :check
    before_action :find_announcement,:only=>[:show,:edit,:destroy,:update]
    def index
		@page_title = "Bulletin Board"
        @announcements = Announcement.all
    end
    def new
		@page_title = "New a New Announcement"
        @announcement = Announcement.new
    end
    def create
        @announcement = Announcement.new(announcement_params)
		@announcement.user_id = get_id
        if @announcement.save
            flash[:notice] = "A new announcement has been created successfully"
            redirect_to user_announcements_path
        else
            flash[:alert] = "Some field is not complete. Please retype again, thanks"
            render :action=>:new
        end
    end
    def show
		@page_title = @announcement.title
    end
    def edit
		if get_id==@announcement.user_id
			@page_title = "Edit "+@announcement.title
		else
			flash[:alert] = "Sorry about that, You are not the user who created this announcement"
			redirect_to user_announcements_path, :method=>:get
		end
    end
    def update
        if @announcement.update(announcement_params)
            flash[:notice] = "The announcement has been updated successfully"
            redirect_to user_announcements_path
        else
            flash[:alert] = "Some field is not complete. Please retype again, thanks"
            render :action=>:edit
        end
    end
    def destroy
		if get_id==@announcement.user_id
	        @announcement.destroy
	        flash[:notice] = "The announcement has been removed successfully"
	        redirect_to user_announcements_path
		else
			flash[:alert] = "Sorry about that, You are not the user who created this announcement"
			redirect_to user_announcements_path, :method=>:get
		end
    end
private
    def find_announcement
        @announcement = Announcement.find(params[:id])
    end
    def announcement_params
        params.require(:announcement).permit(:title,:content,:department_id,:user_id)
    end
    def check
        if !logged_in
            redirect_to announcements_url
        end
    end
end

demo/app/controllers/user/departments_controller.rb
class User::DepartmentsController < ApplicationController
    before_action :check
    before_action :find_department,:only=>[:show,:edit,:destroy,:update]
    def index
        @page_title = "Departments"
        @departments = Department.all
    end
    def new
        @page_title = "New a Department"
        @department = Department.new
    end
    def create
        @department = Department.new(department_params)
        if @department.save
            flash[:notice] = "A new department has been created successfully"
            redirect_to user_announcements_url
        else
            flash[:alert] = "Some field is not complete. Please retype again, thanks"
            render :action=>:new
        end
    end
    def show
        @page_title = @department.d_name
    end
    def edit
        @page_title = "Edit "+@department.d_name
    end
    def update
        if @department.update(department_params)
            flash[:notice] = "The department has been updated successfully"
            redirect_to user_departments_path,:method=>:get
        else
            flash[:alert] = "Some field is not complete. Please retype again, thanks"
            render :action=>:edit
        end
    end
    def destroy
        @department.destroy
        flash[:notice] = "The department has been removed successfully"
        redirect_to user_departments_path,:method=>:get
    end
private
    def find_department
        @department = Department.find(params[:id])
    end
    def department_params
        params.require(:department).permit(:d_name)
    end
    def check
        if !logged_in
            redirect_to announcements_url
        end
    end
end

demo/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check
    before_action :find_user, :only=>[:show,:edit,:update]
    def index
        if logged_in
            @id=get_id
            redirect_to user_path(@id)
        else
            redirect_to user_announcements_url
        end
    end
    def new
        if logged_in
            flash[:alert] = "You are already a user."
            redirect_to user_announcements_url
        else
            @page_title = "New an User"
            @user=User.new
        end
    end
    def show
        if logged_in
            @page_title = @user.name+"'s profile"
        else
            flash[:alert] = "No authorized User."
            redirect_to announcements_url,:method=>:get
        end
    end
    def create
        @user=User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome~"
            #redirect_to user_path(@user), :method=>:get
            log_in(@user)
            redirect_to user_announcements_path, :method=>:get
        else
            render :action=>:new
        end
    end
    def edit
        @page_title = "Edit "+@user.name+"'s profile"
    end
    def update
        if @user.update(user_name_email_params)
            flash[:notice] = "Successfully updated..."
            redirect_to user_path(@user), :method=>:get
        else
            flash[:alert] = "Something Wrong"
            render :action=>:edit
        end
    end
    def allpost
        if logged_in
            @user_id = get_id
            @announcements = Announcement.where(:user_id=>@user_id)
        else
            redirect_to announcements_url, :method=>:get
        end
    end
private
    def find_user
        @user = User.find(params[:id])
    end
    def user_params
        params.require(:user).permit(:name,:email,:account,:password,:password_confirmation)
    end
    def user_name_email_params
        params.require(:user).permit(:name,:email)
    end
    def check
        if(!logged_in)
            redirect_to announcements_url,:method=>:get
        end
    end
end

demo/app/helpers/user/announcements_helper.rb
module User::AnnouncementsHelper

end

demo/app/helpers/user/departments_helper.rb
module User::DepartmentsHelper
end

demo/app/helpers/users_helper.rb
module UsersHelper
end

demo/app/views/users/_form.html.erb
<%= data.text_field :name %>
<%= data.text_field :email %>
<%= data.text_field :account %>
<%= data.password_field :password, help: "Must be at least 6 characters long"  %>
<%= data.password_field :password_confirmation %>
<% if @user.errors.any? %>
    <ul class="h4">
        <% @user.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>

demo/app/views/users/allpost.html.erb
<nav class="navbar navbar-link">
    <% if logged_in%>
        <span style="font-size: 2rem">Hello, <%= current_user.name%></span>
        <br />
        <div class="btn-group btn-group-lg">
            <%= link_to "Edit profile", edit_user_path(current_user), class:'btn btn-success'%>
            <%= link_to "Show profile", user_path(current_user), class:'btn btn-info' %>
            <%= link_to "Log Out", login_url,:method=>:delete, class:'btn btn-danger' %>
        </div>
    <% else %>
        <%= link_to "Login", login_url, :class=>'btn btn-info'%>
    <% end %>
</nav>
<p class="h2" style="color:Blue;">Below are what you have posted.</p>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover h4">
      <tr>
        <td>Updated Date</td>
        <td>Title</td>
        <td>Department</td>
    	<td>Options</td>
    	</td>
      </tr>
      <% @announcements.each do |announcement| %>
          <tr>
              <td>
                  <%= announcement.updated_at.localtime.strftime("%Y/%m/%d %H:%M:%S") %>
              </td>
              <td>
                  <%= link_to announcement.title, user_announcement_path(announcement), :method=>:get %>
              </td>
              <td>
                  <%= Department.find(announcement.department_id).d_name %>
              </td>
              <td>
                  <% if session[:user_id]==announcement.user_id %>
                      <div class="btn-group">
                          <%= link_to "Edit", edit_user_announcement_path(announcement), class:'btn btn-success'%>
                          <%= link_to "Delete", user_announcement_path(announcement), :method=>:delete,:data=>{:confirm=>"Are you sure ?"}, class:'btn btn-danger'%>
                      </div>
                  <% else %>
                          Not available
                  <% end %>
              </td>
          </tr>
      <% end %>
    </table>
</div>
<span><%= link_to "New Announcement", new_user_announcement_path,  class:'btn btn-primary btn-lg' %></span>
<span><%= link_to "Back to announcements manage page", user_announcements_url, :class=>"btn btn-info btn-lg" %></span>

demo/app/views/users/edit.html.erb
<%= bootstrap_form_for @user, :url=>user_path(@user), :method=>:patch do |user_data| %>
	<br />
	<%= user_data.text_field :name%>
	<%= user_data.text_field :email%>
	<%= user_data.submit "Update",:class=>"btn btn-primary" %>
<% end %>
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>

demo/app/views/users/new.html.erb
<%= bootstrap_form_for @user, :url=>users_path,:method=>:post do |user_data| %>
<%= render :partial=>"form", :locals=>{:data=>user_data} %>
<br />
<%= user_data.submit "Create new user",:class=>"btn btn-success"%>
<% end %>

demo/app/views/users/show.html.erb
<p class="h3">
    ID : <%= @user.id %>
</p>
<p class="h3">
    Name : <%= @user.name %>
</p>
<p class="h3">
    Email : <%= @user.email %>
</p>
<p style="font-size: 2rem;color:Red">
    Update_Date : <%= @user.updated_at.strftime("%Y/%m/%d %H:%M:%S") %>
</p>
<p style="font-size: 2rem">
    Create_Date &nbsp: <%= @user.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
</p>
<nav class="navbar">
    <%= link_to "Go announcements index page", user_announcements_path ,:class=>"btn btn-info navbar-btn btn-lg"%>
</nav>